version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"

sphinx:
  fail_on_warning: false
  configuration: docs/source/conf.py

python:
  # Install our python package before building the docs
  install:
    - pip install numpy>=1.22.3
    - method: pip
      path: .
      extra_requirements:
        - docs
